### ISSUE TITLE
"image" lines from input_gen2

### ISSUE THREAD

**Issue by biochem-fan** [cppxfel/cppxfel#1]
https://github.com/cppxfel/cppxfel/blob/master/command_line/input_gen2.py#L136
Do you mean baseFile here? input_gen.py uses baseFile.

**Comment by helenginn** [comment]
input_gen2.py has been renamed gen.py (input_gen.py will be retired when I am happy with gen.py).
You are right, baseFile should have been used here, and it has been switched back. Thanks!
